install.packages(c("assertthat",
                   "DBI",
                   "dplyr",
                   "EML",
                   "frictionless",
                   "glue",
                   "htmltools",
                   "leaflet",
                   "lifecycle",
                   "lubridate",
                   "purrr",
                   "RColorBrewer",
                   "readr",
                   "rlang",
                   "RSQLite",
                   "stringr",
                   "tidyr",
                   "tools",
                   "utils",
                   "uuid",
                   "covr",
                   "knitr",
                   "rmarkdown",
                   "testthat",
                   "knitr",
                   "devtools"), dependencies = TRUE)

devtools::install_github("inbo/camtraptor")